In [47]:
import pandas as pd
import numpy as np
from math import comb

In [78]:
df = pd.read_csv('data_with_feedback.csv')

diff = np.abs(df['deg1'] - df['deg2'])
deg_diff = np.minimum(diff, 360 - diff)
df['angle_diff'] = deg_diff

df.head()

   session_no  trial_no  deg1  deg2  is_correct  angle_diff
0           1         1    15   330           1          45
1           1         2    60   195           1         135
2           1         3    60     0           1          60
3           1         4   120     0           0         120
4           1         5    60   330           1          90

### all angles + random shapes

In [49]:
vec_random_all = df['is_correct'].astype(int).tolist()

print(vec_random_all)
print("Length:", len(vec_random_all))

[1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0]
Length: 100

In [50]:
number_correct_random_all = sum(vec_random_all)
number_incorrect_random_all = 100 - number_correct_random_all

print("Correct:", number_correct_random_all)
print("Incorrect:", number_incorrect_random_all)

Correct: 64
Incorrect: 36

In [51]:
p_value_random_all = sum(comb(100, k) * 0.5**100 for k in range(number_correct_random_all, 101))
print("p value:", p_value_random_all)

p value: 0.0033185602579630636

### filtered angle + random shapes

In [52]:
filtered_angle_value = 45

In [76]:
angle_filtered_df = df[deg_diff > filtered_angle_value].copy()

angle_filtered_df.head()

   session_no  trial_no  deg1  deg2  is_correct  angle_diff
1           1         2    60   195           1         135
2           1         3    60     0           1          60
3           1         4   120     0           0         120
4           1         5    60   330           1          90
5           1         6    15    90           0          75

In [54]:
vec_angle_filtered = angle_filtered_df['is_correct'].astype(int).tolist()

print(vec_angle_filtered)
print("Length:", len(vec_angle_filtered))

[1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
Length: 70

In [55]:
number_correct_random_angle = sum(vec_angle_filtered)
number_incorrect_random_angle = len(vec_angle_filtered) - number_correct_random_angle

print("Correct:", number_correct_random_angle)
print("Incorrect:", number_incorrect_random_angle)

Correct: 40
Incorrect: 30

In [56]:
p_value_random_angle = sum(comb(len(vec_angle_filtered), k) * (0.5**len(vec_angle_filtered)) for k in range(number_correct_random_angle, len(vec_angle_filtered)+1))
print("p value:", p_value_random_angle)

p value: 0.140989460896828

### random shapes without instant feedback

In [57]:
df2 = pd.read_csv('data_without_feedback.csv')

diff_2 = np.abs(df2['deg1'] - df2['deg2'])
deg_diff_2 = np.minimum(diff_2, 360 - diff_2)
df2['angle_diff'] = deg_diff_2

df2.head()

   session_no  trial_no  deg1  deg2  is_correct  angle_diff
0           1         1   240    75           0         165
1           1         2    30    60           1          30
2           1         3   165   300           0         135
3           1         4   150   210           0          60
4           1         5   300     0           0          60

### all angles + random shapes

In [58]:
vec_random_all_2 = df2['is_correct'].astype(int).tolist()

print(vec_random_all_2)
print("Length:", len(vec_random_all_2))

[0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1]
Length: 50

In [59]:
number_correct_random_all_2 = sum(vec_random_all_2)
number_incorrect_random_all_2 = 50 - number_correct_random_all_2

print("Correct:", number_correct_random_all_2)
print("Incorrect:", number_incorrect_random_all_2)

Correct: 28
Incorrect: 22

In [60]:
p_value_random_all_2 = sum(comb(50, k) * 0.5**50 for k in range(number_correct_random_all_2, 51))
print("p value:", p_value_random_all_2)

p value: 0.23994383084916393

### filtered angle value + random shapes

In [61]:
filtered_angle_value_2 = 45

In [62]:
angle_filtered_df_2 = df2[deg_diff_2 > filtered_angle_value_2].copy()

angle_filtered_df_2.head()

   session_no  trial_no  deg1  deg2  is_correct  angle_diff
0           1         1   240    75           0         165
2           1         3   165   300           0         135
3           1         4   150   210           0          60
4           1         5   300     0           0          60
5           1         6   150    75           0          75

In [63]:
vec_angle_filtered_2 = angle_filtered_df_2['is_correct'].astype(int).tolist()

print(vec_angle_filtered_2)
print("Length:", len(vec_angle_filtered_2))

[0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1]
Length: 39

In [64]:
number_correct_random_angle_2 = sum(vec_angle_filtered_2)
number_incorrect_random_angle_2 = len(vec_angle_filtered_2) - number_correct_random_angle_2

print("Correct:", number_correct_random_angle_2)
print("Incorrect:", number_incorrect_random_angle_2)

Correct: 20
Incorrect: 19

In [65]:
p_value_random_angle_2 = sum(comb(len(vec_angle_filtered_2), k) * (0.5**len(vec_angle_filtered_2)) for k in range(number_correct_random_angle_2, len(vec_angle_filtered_2)+1))
print("p value:", p_value_random_angle_2)

p value: 0.5

### One familiar shape without feedback

In [66]:
df3 = pd.read_csv('data_one_familiar.csv')

diff_3 = np.abs(df3['deg1'] - df3['deg2'])
deg_diff_3 = np.minimum(diff_3, 360 - diff_3)
df3['angle_diff'] = deg_diff_3

df3.head()

   session_no  trial_no  deg1  deg2  is_correct  angle_diff
0           1         1   135   270           0         135
1           1         2   300    75           1         135
2           1         3    30   270           1         120
3           1         4    30   345           1          45
4           1         5   240     0           1         120

In [67]:
vec_one_familiar = df3['is_correct'].astype(int).tolist()

print(vec_one_familiar)
print("Length:", len(vec_one_familiar))

[0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
Length: 50

In [68]:
number_correct_one_familiar = sum(vec_one_familiar)
number_incorrect_one_familiar = 50 - number_correct_one_familiar

print("Correct:", number_correct_one_familiar)
print("Incorrect:", number_incorrect_one_familiar)

Correct: 47
Incorrect: 3

In [69]:
p_value_one_familiar = sum(comb(50, k) * 0.5**50 for k in range(number_correct_one_familiar, 51))
print("p value:", p_value_one_familiar)

p value: 1.8541612689659814e-11

### filtered angle value + one familiar shape

In [70]:
filtered_angle_value_3 = 45

In [71]:
angle_filtered_df_3 = df3[deg_diff_3 > filtered_angle_value_3].copy()

angle_filtered_df_3.head()

   session_no  trial_no  deg1  deg2  is_correct  angle_diff
0           1         1   135   270           0         135
1           1         2   300    75           1         135
2           1         3    30   270           1         120
4           1         5   240     0           1         120
5           1         6    45   285           0         120

In [72]:
vec_angle_filtered_3 = angle_filtered_df_3['is_correct'].astype(int).tolist()

print(vec_angle_filtered_3)
print("Length:", len(vec_angle_filtered_3))

[0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Length: 37

In [73]:
number_correct_random_angle_3 = sum(vec_angle_filtered_3)
number_incorrect_random_angle_3 = len(vec_angle_filtered_3) - number_correct_random_angle_3

print("Correct:", number_correct_random_angle_3)
print("Incorrect:", number_incorrect_random_angle_3)

Correct: 35
Incorrect: 2

In [74]:
p_value_random_angle_3 = sum(comb(len(vec_angle_filtered_3), k) * (0.5**len(vec_angle_filtered_3)) for k in range(number_correct_random_angle_3, len(vec_angle_filtered_3)+1))
print("p value:", p_value_random_angle_3)

p value: 5.122274160385132e-09